### ISSUE TITLE
这个工具支持生成android sparse格式的镜像么

### ISSUE THREAD

**Issue by addhaloka** [hsiangkao/erofs-utils#3]
或者说有没类似erofs2simg的工具, 谢谢

**Comment by hsiangkao** [comment]
可以直接使用Android的img2simg

**Comment by addhaloka** [comment]
> 可以直接使用Android的img2simg

不知道erofs是否像ext4一样存在未使用的block, 如果是img2simg其实不适用

**Comment by hsiangkao** [comment]
> > 可以直接使用Android的img2simg
> 
> 不知道erofs是否像ext4一样存在未使用的block, 如果是, 那img2simg其实不适用
> 比如ext2simg, 能生成比img2simg更优的稀疏镜像

我觉得这个你可以自己先试试，我们一直用img2simg。
erofs的block利用率很高，sparse格式对于erofs本身几乎没什么用途主要起作用的也就data跟vb的gap。
如果你有兴趣也可以帮忙开发这个功能，对于我来说这个特性优先级比较低，因为运行时省不了多少时间和空间。

**Comment by hsiangkao** [comment]
> > > 可以直接使用Android的img2simg
> > 
> > 
> > 不知道erofs是否像ext4一样存在未使用的block, 如果是, 那img2simg其实不适用
> > 比如ext2simg, 能生成比img2simg更优的稀疏镜像
> 
> 我觉得这个你可以自己先试试，我们一直用img2simg。
> erofs的block利用率很高，sparse格式对于erofs本身几乎没什么用途主要起作用的也就data跟vb的gap。
> 如果你有兴趣也可以帮忙开发这个功能，对于我来说这个特性优先级比较低，因为运行时省不了多少时间和空间。

加一句，如果simg在erofs上发挥了非常大的作用（除了最后的vb部分），感觉应该属于bug需要解决。
erofs格式不应该出现连续的空白或者填充块, simg只是个传输格式，erofs更在乎最终磁盘上的形态是不是紧凑。

**Comment by google-mirror** [comment]
@hsiangkao 你了解ext4么, 想请教下为何cp命令复制文件和自行代码open, read, write最终文件占用的blocks会不一样呢?文件长度和内容都是一致的, md5一致, 但占用的blocks差了72个, 想不通

**Comment by hsiangkao** [comment]
> @hsiangkao 你了解ext4么, 想请教下为何改变一个字节为何导致占用的blocks变化巨大呢?
> 文件长度7816288, 把第6184959字节改为0, blocks不变, 把第6184959+1字节改为0, blocks立马增加了8个。
> 
> Filesystem features: ext_attr resize_inode dir_index filetype extent flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize
> Filesystem flags: signed_directory_hash

并不是很了解发生了什么，但我猜你可以e2fsprogs的debugfs工具看一下这个文件究竟发生了什么变化。

**Comment by google-mirror** [comment]
@hsiangkao 谢谢大佬, 用debugfs看了, 原文件EXTENTS有两段, 中间断开了, 修改之后文件的EXTENTS变成一段了, 难道是被压缩了?只修改内容不应该导致blocks改变吧

**Comment by hsiangkao** [comment]
> @hsiangkao 谢谢大佬, 用debugfs看了, 原文件EXTENTS有两段, 中间断开了, 修改之后文件的EXTENTS变成一段了, 难道是被压缩了?只修改内容不应该导致blocks改变吧

我猜可能原文件原来中间有洞，你写了一个0，然后就分配了具体的磁盘块。
