### ISSUE TITLE
A couple of questions on EROFS

### ISSUE THREAD

**Issue by donmark8** [hsiangkao/erofs-utils#6]
Hi Gao Xiang,

Good works on EROFS! I have a couple of questions, hope you can help to answer them.
1. Comparing with lz4, lzma will make the size small, but decompression time will be longer, do you have any benchmark test results for lz4 and lzma in terms of size and performance.
2. Do you plan to add lzma support for EROFS-Utils in buildroot? 
3. Do you plan to add zstd support for EROFS in kernel?

Thanks,
--Don

**Comment by hsiangkao** [comment]
1. yeah I did, actually lzma and lz4 are used for different scenarios, lzma is still an experimental feature which is used for small embedded devices like routers or other non I/O sensitive scenarios, but lz4 is for high-performance scenarios.
2. I plan to do, but it really relies on a new stable XZ-utils release, which is still WIP;
3. I plan to do, but I don't want to add a plain algorithm without any optimization and adaption. It still need some time to evaluate and do some like inplace I/O optimization.

**Comment by donmark8** [comment]
Thanks for the reply. I am glad to hear that you will work on zstd for kernel and add more supports in buildroot. Keep up the good works!

**Comment by firasuke** [comment]
Is this still being worked on? The only thing stopping me from adopting EROFS is that it lacks support for zstd (SquashFS is compressing much better due to having zstd as an option).

**Comment by hsiangkao** [comment]
> Is this still being worked on? The only thing stopping me from adopting EROFS is that it lacks support for zstd (SquashFS is compressing much better due to having zstd as an option).

If you think zstd support is vitally important, I can only say it's still working in progress.
But I cannot give an accurate timetable for Zstd.

**Comment by firasuke** [comment]
> > Is this still being worked on? The only thing stopping me from adopting EROFS is that it lacks support for zstd (SquashFS is compressing much better due to having zstd as an option).
> 
> If you think zstd support is vitally important, I can only say it's still working in progress. But I cannot give an accurate timetable for the optimial Zstd (Cc @Cyan4973).

I really think zstd support is important, and I appreciate that you are working on it. No need for a timetable, I am just checking if it'll be supported in the first place, or if it got dropped.

Thanks for your time and effort on this!

**Comment by hsiangkao** [comment]
> > > Is this still being worked on? The only thing stopping me from adopting EROFS is that it lacks support for zstd (SquashFS is compressing much better due to having zstd as an option).
> > 
> > 
> > If you think zstd support is vitally important, I can only say it's still working in progress. But I cannot give an accurate timetable for the optimial Zstd (Cc @Cyan4973).
> 
> I really think zstd support is important, and I appreciate that you are working on it. No need for a timetable, I am just checking if it'll be supported in the first place, or if it got dropped.

It's still considered but I don't have an accurate finish time.

> 
> Thanks for your time and effort on this!

Thanks for your request too.
