### ISSUE TITLE
Backport erofs to kernel 4.9

### ISSUE THREAD

**Issue by donmark8** [hsiangkao/erofs-utils#7]
Do you know if erofs is backported to kernel 4.9? If not, how difficult to do that? Thanks

**Comment by hsiangkao** [comment]
my previous employer once had in-house 4.9 products, but that is quite old.

https://download-c1.huawei.com/download/downloadCenter?downloadId=101094&version=438732&siteCode=worldwide
Hulk-AL10E_PIE

anyway, 4.9 kernel is too old for me to consider, we're in 5.19 cycle now.

**Comment by donmark8** [comment]
Thank you so much for the link, it's very helpful. The reason I would like to try 4.9 erofs is we still use kernel 4.9 in our products. 
Really appreciate your help!

**Comment by donmark8** [comment]
Thank you for your advice. You are right, after I added that 4.9 erofs in our platform, I was able to mount a file created by using mkfs.erofs 1.0 under ubuntu 20.04, but got Input/output error when trying to access the mounted directory, it looked like the format is not compatible. I am going to backport more the latest patches to 4.9, see if I can make it compatible with at least mkfs.erofs 1.0.

**Comment by xiao-k233** [comment]
> 谢谢你的建议。你是对的，在我的平台中添加了 4.9 erofs 后，我能够在 ubuntu 20.04 下挂载使用 mkfs.erofs 1.0 创建的文件，但在尝试访问挂载目录时出现输入/输出错误，看起来格式不兼容。我将把更多最新的补丁向后移植到 4.9，看看我是否可以使其至少与 mkfs.erofs 1.0 兼容。
> 
> 顺便说一句。是否可以将 EROFS 向后移植到内核 4.4 或 3.10？我们的设备运行在非常旧的内核上，而那些旧平台确实需要提高性能。您是否碰巧有这些内核的向后移植？

so，can you share your 4.9 backport?
